# We don't need a complete pyproject.toml, only one to specify the entries normally provided by the entry_points.console_scipts field in setup.py.
[project]
name = "httpie"

[project.scripts]
http = "httpie.__main__:main"
https = "httpie.__main__:main"
httpie = "httpie.manager.__main__:main"
