name: Setup Tangram CI Directory
description: Configure /opt/tangram as the Tangram build directory for CI

runs:
  using: composite
  steps:
    - name: Create /opt/tangram directory
      shell: bash
      run: |
        sudo mkdir -p /opt/tangram/bin
        sudo chown -R "$(whoami)" /opt/tangram

    - name: Write empty config
      shell: bash
      run: echo '{}' > /opt/tangram/config.json

    - name: Create tangram wrapper
      shell: bash
      run: |
        cat > /opt/tangram/bin/tangram <<'WRAPPER'
        #!/bin/sh
        exec tangram --directory /opt/tangram --config /opt/tangram/config.json "$@"
        WRAPPER
        chmod +x /opt/tangram/bin/tangram

    - name: Set TG_EXE
      shell: bash
      run: echo "TG_EXE=/opt/tangram/bin/tangram" >> "$GITHUB_ENV"
