[workspace]
members = ["packages/cc_proxy", "packages/ld_proxy", "packages/wrapper"]
resolver = "2"

[workspace.lints.clippy]
pedantic = "warn"
missing_errors_doc = "allow"
missing_panics_doc = "allow"
missing_safety_doc = "allow"

[workspace.dependencies]
async-recursion = "1"
byteorder = "1"
clap = { version = "4", features = ["derive"] }
fnv = "1"
futures = "0.3"
goblin = "0.8"
itertools = "0.12"
libc = "0.2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tangram_client = { git = "https://github.com/tangramdotdev/tangram", rev = "ab1d86be29611c8a23c8d70673a13b3a12419330" }
tangram_error = { git = "https://github.com/tangramdotdev/tangram", rev = "ab1d86be29611c8a23c8d70673a13b3a12419330" }
tokio = { version = "1", default-features = false, features = [
  "rt",
  "macros",
  "fs",
  "parking_lot",
] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["json", "parking_lot"] }
xattr = "1"

tangram_wrapper = { path = "packages/wrapper" }
tangram_cc_proxy = { path = "packages/cc_proxy" }
tangram_ld_proxy = { path = "packages/ld_proxy" }

[profile.release]
codegen-units = 1
lto = true
opt-level = "z"
panic = "abort"
strip = true
