[package]
name = "tangram_cc_proxy"
version = "0.0.0"
edition = "2021"

[dependencies]
futures = { workspace = true }
itertools = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tangram_client = { workspace = true }
tangram_error = { workspace = true }
tokio = { workspace = true }
