[package]
name = "tangram_rustc_proxy"
authors = ["Tangram <root@tangram.dev>"]
description = "Userspace utilities for the Tangram standard library"
edition = "2021"
homepage = "https://www.tangram.dev"
license = "MIT"
publish = false
repository = "https://github.com/tangramdotdev/packages"
rust-version = "1.80.0"
version = "0.0.0"


[features]
tracing = ["dep:tracing", "dep:tracing-subscriber"]

[dependencies]
fnv = "1"
futures = "0.3"
itertools = "0.13"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tangram_client = { default-features = false, git = "https://github.com/tangramdotdev/tangram", rev = "d805739e2030a8e2f5f2f062542f69e3a65dab55" }
tokio = { version = "1", default-features = false, features = [
  "rt",
  "fs",
] }
tracing = { version = "0.1", optional = true }
tracing-subscriber = { version = "0.3", features = ["json"], optional = true }
