name: Test Packages
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      [ main ]
jobs:
  test-packages:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]

    name: Test packages on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    env:
      CARGO_INCREMENTAL: 0
    
    steps:
    - name: Checkout packages repository
      uses: actions/checkout@v4

    - name: Checkout tangram repository
      uses: actions/checkout@v4
      with:
        repository: tangramdotdev/tangram
        path: tangram

    - name: Install Rust
      run: rustup update

    - uses: Swatinem/rust-cache@v2

    - name: Install Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest

    - name: Install Dependencies
      run: cd tangram && bun install --frozen-lockfile

    - name: Build Tangram
      run: |
        cargo build --release --manifest-path tangram/Cargo.toml
        echo "$PWD/target/release" >> $GITHUB_PATH

    - name: Verify Tangram works
      run: tg --version
